sudo: false
cache: bundler

before_script:
  - mysql -e 'create database hozr_test;'
  - cp config/database.yml.travis-ci config/database.yml
  - bundle exec rake db:schema:load

env:
  - DB=mysql

script: "bundle exec rake spec"

bundler_args: "--binstubs --without development"

# IRC notification
notifications:
  irc: "irc.freenode.org#cyt"
